version: "3.5"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
     # volumes: 
       # - rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    # volumes: 
    #   - seq:/data
volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  mongo:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local