version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: mym-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
  redis:
    image: redis:latest
    container_name: mym-redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
  mongodb_container:
    container_name: mym-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mym-rabbit
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672
volumes:
  mongodb_data_container: