# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: ""

replicaCount: 1

image:
  repository: hqharbor.lcwaikiki.com/gb/gb-sqlchatbot-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: <TagPlaceholder>

imagePullSecrets:
  - name: hqgbregistry

envVars: {}

## @param volumes 
volumes: {}
  # - name: mymkafka
  #   secret:
  #     secretName: kafka-certificates

volumeMounts: {}
  # - name: mymkafka
  #   mountPath: "/usr/local/share/ca-certificates/kafka"
  #   readOnly: true

restartPolicy: Always

selectorLabels: 
  app: "gb-sqlchatbot-service"
  applicationtype: "backend"
  devlanguage: "csharp"

podAnnotations: {}

service:
  type: ClusterIP
  port: 80


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: app.lcwaikiki.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "200m"

autoscaling:
  enabled: false
  # targetMemoryUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

istio:
  enabled: false
  namespace: cs-dev-shared
  virtualService:
    gateways: []
    # - mymgateway
    hosts: []
    # - demo-dev.apis.test.lcwaikiki.com
    # - demo.gw.dev.lcwaikiki.com  
    http: {}
      # matchUriPrefix: /demo/producer
      # route: 
      #   - destination:
      #       host: <servicename>.<namespace>.svc.cluster.local

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: worker
              operator: In
              values:
                - "true"

annotations:
   sidecar.istio.io/inject: "true"  
